SELECT 
A.NPWP,
A.KPP,
A.CABANG,
A.BULAN,
A.TAHUN,
A.TANGGAL,
A.NOMINAL,
B.NAMA,
B.JENIS,
B.STATUS,
C.NAMA as NAMA_KLU,
D.URAIAN
FROM SPMKP AS A
LEFT JOIN WP AS B
ON A.npwp = B.npwp
AND A.KPP = B.KPP
AND A.CABANG = B.CABANG
	LEFT JOIN KLU C 
    ON B.KLU = C.KODE
		LEFT JOIN MAP D
        ON A.KDMAP = D.KDMAP;